services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "CargoDelivery"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
    - postgres-data:/var/lib/postgresql/data

    ports:
    - "5432:5432"

volumes:
  postgres-data: